name: 'AVM Fix Action'
description: 'Ensures that AVM Fix has been applied'

inputs:
  github-token:
    description: 'GitHub Token'
    required: true

runs:
  using: 'composite'
  steps:
    # Step 1: Add execute permissions to avm.sh in the root directory
    - name: Add execute permissions to avm.sh
      shell: bash
      run: chmod +x avm.sh

    # Step 2: Run the avm.sh script
    - name: Run avmfix
      shell: bash
      run: ./avm.sh

    # # Step 3: Detect changes after running the fix
    # - name: Detect changes
    #   shell: bash
    #   run: |
    #     if [ -z "$(git status -s)" ]; then
    #       echo "No changes detected"
    #       exit 0
    #     else
    #       echo "AVM Fix changes detected, please commit and push the changes."
    #       exit 1
    #     fi
