---
  name: e2e test
  
  on:
    pull_request:
      types: ['opened', 'reopened', 'synchronize']
    merge_group:
    workflow_dispatch:
  
  permissions:
    contents: read
    id-token: write
  
  jobs:
    getexamples:
      if: github.event.repository.name != 'terraform-azurerm-avm-template'
      runs-on: ubuntu-latest
      outputs:
        examples: ${{ steps.getexamples.outputs.examples }}
      steps:
        - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
        - name: get examples
          id: getexamples
          uses: Azure/terraform-azurerm-avm-template/.github/actions/e2e-getexamples@main
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
  
    testexamples:
      if: github.event.repository.name != 'terraform-azurerm-avm-template'
      #runs-on: [ self-hosted, 1ES.Pool=ff314ac9fce031b9e7f5dde283f515666e148ae7 ]
      runs-on: self-hosted
      needs: getexamples
      environment: test
      env:  
        TF_IN_AUTOMATION: 1
        TF_VAR_enable_telemetry: false
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      # strategy:
      #   matrix:
      #     example: ${{ fromJson(needs.getexamples.outputs.examples) }}
      #   fail-fast: false
      strategy:
        matrix:
          example:
            - "examples/complete"
            - "examples/default"
            #- "examples/storage-account"
        fail-fast: false
      steps:
        - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
  
        # - name: Set up Terraform
        #   run: |
        #     sudo apt-get update -y
        #     sudo apt-get install -y software-properties-common
        #     sudo apt-add-repository --yes --update ppa:ansible/ansible
        #     sudo apt-get update -y
        #     sudo apt-get install -y terraform
        - name: Set up Terraform on Windows
          run: |
            # Install Chocolatey if not already installed
            Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
            if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
              [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
              iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
            }

            # Install Terraform using Chocolatey
            choco install terraform -y

            # Verify the installation
            terraform -version
          shell: powershell
        
        # Uninstall any existing Git packages
        - name: Uninstall Existing Git Packages
          run: |
            Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
            choco uninstall git.install -y || echo "No previous installation of git.install found."
            choco uninstall git -y || echo "No previous installation of git found."
          shell: powershell

        # Remove any residual Git files
        - name: Remove Git Residual Files
          run: |
            Remove-Item -Path "C:\Program Files\Git" -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item -Path "C:\Program Files (x86)\Git" -Recurse -Force -ErrorAction SilentlyContinue
            Remove-Item -Path "C:\ProgramData\chocolatey\lib\git*" -Recurse -Force -ErrorAction SilentlyContinue
          shell: powershell

        # Install Git using Chocolatey without `git.install`
        - name: Install Git Using Chocolatey
          run: |
            Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
            choco install git -y --params "/GitAndUnixToolsOnPath"
            git --version
          shell: powershell

        # If Chocolatey fails, manually install Git as a fallback
        - name: Install Git Manually (Fallback)
          if: failure()
          run: |
            Invoke-WebRequest -Uri https://github.com/git-for-windows/git/releases/download/v2.46.2.windows.1/Git-2.46.2-64-bit.exe -OutFile C:\git-installer.exe
            Start-Process -FilePath "C:\git-installer.exe" -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART", "/NOCANCEL", "/SP-" -NoNewWindow -Wait
            $env:PATH += ";C:\Program Files\Git\bin"
            git --version
          shell: powershell

             
        
  
        - name: Initialize Terraform for example
          run: |
            terraform init -backend=false -reconfigure
          working-directory: ${{ matrix.example }}
  
        - name: Validate Terraform example
          run: |
            terraform validate
          working-directory: ${{ matrix.example }}
  
        - name: Plan Terraform example
          run: |
            terraform plan -input=false -out=tfplan
          working-directory: ${{ matrix.example }}
  
        - name: Apply Terraform example
          run: |
            terraform apply -input=false tfplan
          working-directory: ${{ matrix.example }}
  
        - name: Destroy Terraform example
          if: always()
          run: |
            terraform destroy -auto-approve
          working-directory: ${{ matrix.example }}
  
    testexamplescomplete:
      if: github.event.repository.name != 'terraform-azurerm-avm-template'
      runs-on: ubuntu-latest
      needs: testexamples
      steps:
        - run: echo "All tests passed"
  