---
  name: e2e test
  
  on:
    pull_request:
      types: ['opened', 'reopened', 'synchronize']
    merge_group:
    workflow_dispatch:
  
  permissions:
    contents: read
    id-token: write
  
  jobs:
    getexamples:
      if: github.event.repository.name != 'terraform-azurerm-avm-template'
      runs-on: ubuntu-latest
      outputs:
        examples: ${{ steps.getexamples.outputs.examples }}
      steps:
        - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
        - name: get examples
          id: getexamples
          uses: Azure/terraform-azurerm-avm-template/.github/actions/e2e-getexamples@main
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
  
    testexamples:
      if: github.event.repository.name != 'terraform-azurerm-avm-template'
      runs-on: self-hosted
      needs: getexamples
      environment: test
      env:  
        TF_IN_AUTOMATION: 1
        TF_VAR_enable_telemetry: false
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      strategy:
        matrix:
          example:
            - "examples/complete"
            - "examples/default"
        fail-fast: false
      steps:
        - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
 
        # Set up Terraform on Windows
        - name: Set up Terraform on Windows
          run: |
            Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
            if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
              [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
              iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
            }
            choco install terraform -y
            terraform -version
          shell: powershell
        
        - name: Install Git on Windows with Detailed Logging
          run: |
            # Ensure the Temp directory exists
            if (-not (Test-Path "C:\Temp")) {
              Write-Output "Creating Temp directory at C:\Temp"
              New-Item -Path "C:\Temp" -ItemType Directory -Force
            } else {
              Write-Output "Temp directory already exists at C:\Temp"
            }
        
            # Define the URL of the Git installer
            $gitInstallerUrl = "https://github.com/git-for-windows/git/releases/download/v2.40.1.windows.1/Git-2.40.1-64-bit.exe"
            
            # Define the path to save the installer
            $installerPath = "C:\Temp\Git-2.40.1-64-bit.exe"
            Write-Output "The installer will be saved to: $installerPath"
            
            # Download the Git installer
            Write-Output "Downloading Git installer from: $gitInstallerUrl"
            try {
              Invoke-WebRequest -Uri $gitInstallerUrl -OutFile $installerPath -UseBasicParsing
              Write-Output "Successfully downloaded the Git installer."
            } catch {
              Write-Output "Failed to download the Git installer."
              Write-Output "Error Message: $($_.Exception.Message)"
              exit 1
            }
        
            # Verify that the installer was downloaded successfully
            if (-not (Test-Path $installerPath)) {
              Write-Output "Installer file does not exist at path: $installerPath"
              exit 1
            }
        
            Write-Output "Starting Git installation silently..."
            # Run the installer silently and capture the process exit code
            try {
              $process = Start-Process -FilePath $installerPath -ArgumentList "/VERYSILENT", "/SUPPRESSMSGBOXES", "/NORESTART" -NoNewWindow -Wait -PassThru
              $exitCode = $process.ExitCode
              Write-Output "Git installer exited with code: $exitCode"
            } catch {
              Write-Output "Git installation encountered an error during execution."
              Write-Output "Error Message: $($_.Exception.Message)"
              exit 1
            }
        
            # Check the exit code to determine success or failure
            if ($exitCode -eq 0) {
              Write-Output "Git installation completed successfully with exit code 0."
            } else {
              Write-Output "Git installation failed with exit code $exitCode."
              exit $exitCode
            }
        
            # Verify Git installation by checking the version
            if (Get-Command git -ErrorAction SilentlyContinue) {
              Write-Output "Git installation successful and git is in the PATH."
              git --version
            } else {
              Write-Output "Git installation failed or git is not in the PATH."
              exit 1
            }
        
            # Clean up the installer after installation
            Write-Output "Cleaning up the installer file..."
            Remove-Item -Path $installerPath -Force
            Write-Output "Installer file removed from $installerPath"
          shell: powershell
        
  
        - name: Initialize Terraform for example
          run: |
            terraform init -backend=false -reconfigure
          working-directory: ${{ matrix.example }}
  
        - name: Validate Terraform example
          run: |
            terraform validate
          working-directory: ${{ matrix.example }}
  
        - name: Plan Terraform example
          run: |
            terraform plan -input=false -out=tfplan
          working-directory: ${{ matrix.example }}
  
        - name: Apply Terraform example
          run: |
            terraform apply -input=false tfplan
          working-directory: ${{ matrix.example }}
  
        - name: Destroy Terraform example
          if: always()
          run: |
            terraform destroy -auto-approve
          working-directory: ${{ matrix.example }}
  
    testexamplescomplete:
      if: github.event.repository.name != 'terraform-azurerm-avm-template'
      runs-on: ubuntu-latest
      needs: testexamples
      steps:
        - run: echo "All tests passed"
  