name: Terraform Linting

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    name: Terraform Linting
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Run Terraform fmt to check formatting
      - name: Terraform fmt - Check formatting
        run: |
          terraform fmt -check

      # Step 3: Install TFLint for linting Terraform files
      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      # Step 4: Run TFLint for Terraform linting
      - name: Terraform lint
        run: |
          tflint

  avmfix:
        runs-on: ubuntu-latest
        steps:
        # Step 1: Checkout the repository
        - name: Checkout repository
          uses: actions/checkout@v4
        
        # Step 2: Run the AVM Fix Action
        - name: Run AVM Fix
          uses: ./.github/actions/avmfix
          