name: Terraform Docs, Formatting, and Linting

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docs:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    name: Documentation Formatting Check (README.md)
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Node.js and npm (for markdownlint)
      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # You can change this to another version if required

      # Step 3: Run markdownlint to check README.md formatting (root directory)
      - name: Markdownlint - Check README.md format
        run: |
          npm install -g markdownlint-cli
          markdownlint "README.md"

  terraform:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    name: Terraform Linting and Formatting
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Terraform (Set up Terraform on Ubuntu)
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Adjust the version if needed

      # Step 3: Run Terraform fmt to check formatting
      - name: Terraform fmt - Check formatting
        run: |
          terraform fmt -check

      # Step 4: Run Terraform validate to check configuration
      - name: Terraform validate - Check configuration
        run: |
          terraform init -backend=false  # Initialize Terraform without a backend
          terraform validate

      # Step 5: Install TFLint for linting Terraform files
      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      # Step 6: Run TFLint for Terraform linting
      - name: Terraform lint
        run: |
          tflint
