name: version-check

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Add execute permissions to the script
      - name: Add execute permissions to version-check-script.sh
        run: chmod +x .github/actions/version-check/version-check-script.sh

      # Step 3: Fetch all tags to ensure they're available
      - name: Fetch all tags
        run: git fetch --tags
    
      # Debugging Step: List all tags (Optional)
      - name: List all git tags
        run: git tag

      # # Debugging Step: List all commits with tags
      # - name: List all commits and tags
      #   run: git log --decorate --oneline --graph --all

      # Step 4: Check version using your custom version-check action
      - name: Check version
        uses: ./.github/actions/version-check 


